--- #YAML:1.0
name:                Video-FrameGrab
version:             0.01
abstract:            Grab a frame from a video
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Temp:                    
    Sysadm::Install:               0.17
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
