--- #YAML:1.0
name:               Video-FrameGrab
version:            0.07
abstract:           Grab a frame or metadata from a video
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0.47
    DateTime::Format::Duration:  1.03
    File::Temp:           ~
    Imager:               0.7
    Log::Log4perl:        1.0
    Sysadm::Install:      0.17
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
